name: EKS CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  Create-And-Log-In-AWS-ECR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create ECR repository
        env: 
          AWS_ECR: ${{ secrets.AWS_ECR }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo $AWS_ECR
          aws ecr create-repository --repository-name $AWS_ECR \
          --image-scanning-configuration scanOnPush=true \
          --region $AWS_REGION || echo "Repository already exists"

      - name: Log in to Amazon ECR
        id: ecr-login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}    
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

  Build-and-Push-Images:
    runs-on: ubuntu-latest
    needs: Create-And-Log-In-AWS-ECR

    steps:
      - name: Set up environment variables
        run: echo "VERSION=v1.0" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          # 현재 버전에서 숫자를 증가시키는 스크립트
          VERSION=$(echo "${{ env.VERSION }}" | awk -F. -v OFS=. '{$NF++;print}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check In Advance
        run: ls -R

      - name: Build and push nginx images
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          cd ./front-app-repo/nginx
          for service in index main login login main order reservation reservationinfo signup; do
            # Docker 이미지를 빌드
            docker build -t ${{ secrets.AWS_ECR }}/nginx-$service:${{ env.VERSION }} -f ./$service/Dockerfile ./$service
            
            # 이미지를 ECR에 태그
            docker tag ${{ secrets.AWS_ECR }}/nginx-$service:${{ env.VERSION }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR }}/nginx-$service:${{ env.VERSION }}
            
            # 이미지를 ECR에 푸시
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR }}/nginx-$service:${{ env.VERSION }}
          done

      - name: Build and push Tomcat images
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          cd ./front-app-repo/Tomcat
          for service in index main login login main order reservationinfo signup; do
            # Docker 이미지를 빌드
            docker build -t ${{ secrets.AWS_ECR }}/tomcat-$service:${{ env.VERSION }} -f ./$service/Dockerfile ./$service
            
            # 이미지를 ECR에 태그
            docker tag ${{ secrets.AWS_ECR }}/tomcat-$service:${{ env.VERSION }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR }}/tomcat-$service:${{ env.VERSION }}
            
            # 이미지를 ECR에 푸시
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR }}/tomcat-$service:${{ env.VERSION }}
          done
