name: IAM Example

on:
  push:
    branches:
      - main

jobs:
  setting_aws_credentials:
    runs-on: ubuntu-latest

    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create IAM Policies from JSON files
        run: |
          echo "Listing IAM policy JSON files in 'iam/policy/*.json'"
          for policy_file in iam/policy/*.json; do
            # Extract policy name from the JSON file name (assuming the file is named as the policy)
            policy_name=$(basename "$policy_file" .json)
            echo "Creating IAM Policy from $policy_name"

            # Create IAM Policy using the JSON definition
            aws iam create-policy \
              --policy-name $policy_name \
              --policy-document file://$policy_file
            
            echo "IAM Policy $policy_name created successfully!"
          done

      - name: List IAM role JSON files
        run: |
          echo "Listing IAM role JSON files in 'iam/role/*.json'"
          ls iam/role/*.json

      - name: Create IAM roles from JSON files
        run: |
          for role_file in iam/role/*.json; do
            # Extract role name from the JSON file name (assuming the file is named as the role)
            role_name=$(basename "$role_file" .json)
            echo "Creating IAM Role from $role_name"
            
            # Create IAM Role using the JSON definition
            aws iam create-role \
              --role-name $role_name \
              --assume-role-policy-document file://$role_file
            
            echo "IAM Role $role_name created successfully!"
          done

      - name: Verify IAM roles
        run: |
          for role_file in iam/role/*.json; do
            role_name=$(basename "$role_file" .json)
            echo "Verifying IAM Role: $role_name"
            aws iam get-role --role-name $role_name
