name: IAM Example

on:
  push:
    branches:
      - main

jobs:
  setting_aws_credentials:
    runs-on: ubuntu-latest
    # defaults: 
    #   run: 
    #     working-directory: iam

    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create IAM Policy from JSON file
        run: |
          POLICY_FILE="/home/runner/work/front-app-repo/front-app-repo/iam/policy/iam_eks_policy.json"
          POLICY_NAME="iam_eks_policy"
          pwd
          echo "Creating IAM Policy from $POLICY_NAME"
          aws iam create-policy \
            --policy-name $POLICY_NAME \
            --policy-document file://$POLICY_FILE

      - name: List IAM role JSON files
        run: |
          echo "Listing IAM role JSON files in './role/*.json'"
          ls ./role/*.json

      - name: Create IAM Role from JSON file
        run: |
          ROLE_FILE="/home/runner/work/front-app-repo/front-app-repo/iam/role/iam_eks_role.json"
          ROLE_NAME="iam_eks_role"
          echo "Creating IAM Role from $ROLE_NAME"
          aws iam create-role \
            --role-name $ROLE_NAME \
            --assume-role-policy-document file://$ROLE_FILE
          echo "IAM Role $ROLE_NAME created successfully!"

      - name: Verify IAM Role
        run: |
          ROLE_NAME="iam_eks_role"
          echo "Verifying IAM Role: $ROLE_NAME"
          aws iam get-role --role-name $ROLE_NAME
